---
- name: include distribution-specific common tasks
  include: "{{ ansible_distribution }}.yaml"

- name: set SELinux booleans to allow for persistent storage
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items: "{{ selinux_bools }}"

# - name: set NetworkManager to not alter DNS configuration
#   lineinfile:
#     path: /etc/NetworkManager/NetworkManager.conf
#     regexp: 'plugins=ifcfg-rh'
#     insertafter: 'dns=none'

- name: deploy resolv.conf template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: update systems
  yum:
    name: '*'
    state: latest

- name: restart server
  shell: ( sleep 3 && /sbin/reboot & )

- name: wait for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30 timeout=90 port=22
  become: false
